// Local
###
GET http://localhost:8080/customers/

###
POST http://localhost:8080/customers HTTP/1.1 
content-type: application/json

{
    "firstname": "Contact",
    "lastName": "Create",
    "phone": "(999)999-9999",
    "address": "PO Box 999999",
    "email": "contact@customer.com",
    "password": "testContact",
    "date_of_birth": "9/09/99",
    "gender": "Female"
}



// Render

###
GET https://weston-341.onrender.com/contacts

###
GET https://weston-341.onrender.com/contacts/63641e2f901aa6b4c08e212f

###
GET https://weston-341.onrender.com/contacts/63641e2f901aa6b4c08e2130

###
GET https://weston-341.onrender.com/contacts/63641e2f901aa6b4c08e2131

###
POST https://weston-341.onrender.com/contacts HTTP/1.1 
content-type: application/json

{
    "firstName":"Westest",
    "lastName":"Testwest",
    "email":"Westest@test.com",
    "favoriteColor":"Testue",
    "birthday":"01-01-01"
}

###
PUT https://weston-341.onrender.com/contacts/636c40fa666d93382b214a36 HTTP/1.1
Content-Type: application/json

{
    "birthday":"02-10-1970",
    "email":"benkjar@gmail.com",
    "favoriteColor":"Orange",
    "firstName":"Benjamin",
    "lastName":"Elsmore"
}

### 
DELETE https://weston-341.onrender.com/contacts/636c40fa666d93382b214a36